services:
  php:
    container_name: ccat-php
    build:
      context: ./docker/php
      args:
        - UID=${UID}
        - GID=${GID}
    ports:
      - "8082:8081"
    volumes:
      - ./:/var/www/ccat-php
